In [2]:
import torch
import numpy as np

In [5]:
x=torch.arange(6).reshape(3,2)

In [6]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [10]:
x[1, 1]

tensor(3)

In [13]:
x[:,1]

<function Tensor.transpose>

In [14]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [15]:
x = torch.arange(10)

In [16]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x = torch.arange(10)

In [24]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x.shape

torch.Size([10])

In [26]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
z = x.view(2,5)

In [28]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
x[0] = 99999
#view will reflect the curretn data

In [30]:
x

tensor([99999,     1,     2,     3,     4,     5,     6,     7,     8,     9])

In [31]:
z

tensor([[99999,     1,     2,     3,     4],
        [    5,     6,     7,     8,     9]])

In [34]:
x.shape

torch.Size([10])

In [36]:
x.view(2,-1)
#auto alligment 2 * 5 =10

tensor([[99999,     1,     2,     3,     4],
        [    5,     6,     7,     8,     9]])

In [40]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])


In [41]:
a

tensor([1., 2., 3.])

In [42]:
a.dtype

torch.float32

In [43]:
a

tensor([1., 2., 3.])

In [44]:
b

tensor([4., 5., 6.])

In [45]:
a + b

tensor([5., 7., 9.])

In [46]:
torch.add(a,b)

tensor([5., 7., 9.])

In [48]:
a.add_(b)
# a = a+b

tensor([ 9., 12., 15.])

In [49]:
a

tensor([ 9., 12., 15.])

In [50]:
a

tensor([ 9., 12., 15.])

In [51]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [52]:
a*b

tensor([ 4., 10., 18.])

In [54]:
a.dot(b)
#dot product

tensor(32.)

In [55]:
#for 2d both tensors must has same shapes

In [56]:
a = torch.tensor([[0,2,4], [1,3,5]])

In [57]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [58]:
b = torch.tensor([[6,7], [8,9], [10,11]])

In [59]:
a.shape

torch.Size([2, 3])

In [60]:
b.shape

torch.Size([3, 2])

In [63]:
torch.mm(a,b)
#metrix multiplication
#or a@b

tensor([[56, 62],
        [80, 89]])

In [64]:
x = torch.tensor([2.,3.,4.,5.])

In [65]:
x

tensor([2., 3., 4., 5.])

In [66]:
x.norm()

tensor(7.3485)

In [67]:
x.numel()

4

In [68]:
len(x)

4

In [69]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [70]:
len(a)
#len does not works for 2d tensrs

2

In [71]:
a.numel()

6