In [1]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'1.1.0'

In [5]:
arr = np.array([1, 2, 3, 4, 5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.dtype

dtype('int32')

In [9]:
x=torch.from_numpy(arr)

In [11]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
x.dtype

torch.int32

In [22]:
arr2d = np.arange(0.0, 12.0)

In [23]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [24]:
arr2d = arr2d.reshape(4, 3)

In [25]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [26]:
x2 = torch.from_numpy(arr2d)

In [27]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [28]:
arr[0] = 99

In [29]:
arr

array([99,  2,  3,  4,  5])

In [31]:
x
#smae place in the memmory

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [32]:
my_arr = np.arange(0.0, 10.0)

In [33]:
my_tensor = torch.tensor(my_arr)

In [34]:
my_tensor2 = torch.from_numpy(my_arr)

In [35]:
my_tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [36]:
my_tensor2

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [37]:
my_arr[0] = 898989

In [38]:
my_tensor2

tensor([8.9899e+05, 1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00,
        6.0000e+00, 7.0000e+00, 8.0000e+00, 9.0000e+00], dtype=torch.float64)

In [39]:
my_tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [48]:
#tensor vs Tensor 
new_arr = np.array([1, 2 , 3])

In [49]:
new_arr.dtype

dtype('int32')

In [50]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [51]:
torch.Tensor(new_arr)
#noew it is float32

tensor([1., 2., 3.])

In [55]:
torch.empty(2, 2)

tensor([[0.0000e+00, 0.0000e+00],
        [3.9306e-28, 4.5915e-41]])

In [58]:
torch.zeros(2, 4, dtype= torch.int64)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

In [60]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [62]:
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [63]:
torch.linspace(0, 18, 12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [64]:
torch.tensor([1, 2, 3, 4, 5])

tensor([1, 2, 3, 4, 5])

In [65]:
my_tensor = torch.tensor([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9])

In [66]:
my_tensor.dtype

torch.int64

In [68]:
my_tensor.type(torch.int64)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
my_tensor.dtype

torch.int64

In [70]:
torch.rand(4, 3)

tensor([[0.4811, 0.3068, 0.8158],
        [0.4782, 0.3572, 0.2366],
        [0.9109, 0.7809, 0.6770],
        [0.9242, 0.1700, 0.6173]])

In [71]:
torch.randn(4, 3)

tensor([[-0.1563,  0.4942,  0.4533],
        [ 0.5127, -0.2482,  2.6420],
        [ 0.7013, -0.5746, -0.7993],
        [-0.7078,  0.6754,  2.0983]])

In [75]:
torch.randint(low=0, high=11, size= (4, 3))

tensor([[9, 9, 9],
        [4, 8, 1],
        [3, 3, 8],
        [3, 6, 5]])

In [76]:
x = torch.zeros(2,5)

In [77]:
x


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [78]:
torch.rand_like(x)
#will produce the same shape as the original

tensor([[0.6759, 0.4223, 0.9323, 0.9429, 0.8700],
        [0.8918, 0.8784, 0.4051, 0.5226, 0.2847]])

In [79]:
torch.randn_like(x)

tensor([[ 0.8752, -0.6649,  0.2676, -0.2271, -1.0404],
        [-0.5131,  0.8764, -0.4942,  1.2966, -0.4555]])

In [81]:
torch.randint_like(x, low=0, high = 20)

tensor([[11., 18.,  9., 11., 12.],
        [ 0.,  1.,  8., 14., 11.]])

In [84]:
torch.manual_seed(42)
torch.rand(2,3)
#it should be on the same cell

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])