In [1]:
import torch

In [2]:
x = torch.tensor(2.0, requires_grad= True)

In [4]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x+1
y

tensor(63., grad_fn=<AddBackward0>)

In [5]:
y.backward()

In [6]:
x.grad
#slope of our polynomial where x =2

tensor(93.)

In [10]:
x = torch.tensor([[1.,2.,3.], [3., 2., 1.]], requires_grad= True)

In [11]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [17]:
y = 3*x +2
#first layer

In [18]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [19]:
z = 2*y**2
#second layer

In [20]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [21]:
out = z.mean()

In [22]:
out

tensor(140., grad_fn=<MeanBackward0>)

In [23]:
out.backward()

In [25]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])