In [1]:
import numpy as np

In [2]:
arr = np. arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr *2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 90

In [17]:
slice_of_arr

array([90, 90, 90, 90, 90, 90])

In [18]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [19]:
arr_copy  = arr.copy()

In [20]:
arr_copy

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 1000

In [22]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [23]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [25]:
arr_2d = np.array([[5, 10 , 15], [20, 25, 30] , [35 , 40 , 45]])


In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d.shape

(3, 3)

In [31]:
arr_2d[1]

array([20, 25, 30])

In [32]:
arr_2d[1][1]

25

In [33]:
arr_2d[1, 1]

25

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
arr_2d[:, :1]

array([[ 5],
       [20],
       [35]])

In [43]:
arr = np.arange(0, 11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# conditional selecting 
arr[arr >4 ]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])