In [2]:
import numpy as np

In [25]:
my_list = [[1,2,3], [4,5,6], [7,8,9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
test=np.array(my_list)
test

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
test.shape

(3, 3)

In [27]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [32]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.ones((5 ,5)) +4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [35]:
np.ones(5) * 100

array([100., 100., 100., 100., 100.])

In [39]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [49]:
np.random.rand(5, 5)

array([[7.82918995, 9.76437562, 4.22895446, 1.60884005, 5.17143692],
       [3.05691639, 7.72371026, 8.68016488, 6.1946631 , 1.5557488 ],
       [0.87610296, 1.21843168, 0.79581535, 2.67835622, 8.28141467],
       [8.07379798, 7.03877112, 9.19855221, 0.60480793, 1.69093343],
       [2.2518714 , 4.75384391, 5.73848742, 0.13217034, 9.46077615]])

In [51]:
np.random.randn(10)

array([ 0.43298178,  0.46561398, -0.67149574, -1.40330201,  0.39264393,
       -0.01241783, -1.97962577, -0.19321993, -1.28822987, -1.3960203 ])

In [53]:
np.random.randint(1 , 100, 10)

array([62, 62, 16,  1, 42, 49, 73, 38, 85, 85])

In [61]:
np.random.seed(42)
np.random.rand(4)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [62]:
arr = np.arange(25)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
ranarr = np.random.randint(0, 50, 10)

In [65]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [66]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
ranarr.max()

39

In [71]:
ranarr.min()

2

In [72]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [73]:
ranarr.argmax()

7

In [74]:
ranarr.argmin()

9

In [75]:
ranarr.dtype

dtype('int32')